CREATE TABLE IF NOT EXISTS `#__encrypted` (
	`id` int(11) unsigned NOT NULL AUTO_INCREMENT,
	`stuff` VARBINARY(271) DEFAULT NULL,
	PRIMARY KEY (`id`)
	)
ENGINE =MyISAM
AUTO_INCREMENT =0
DEFAULT CHARSET =utf8;